### ISSUE TITLE
Document which fragment of SPARQL 1.1 is currently supported

### ISSUE THREAD

**Issue by bcogrel** [ontop/ontop-website#13]
Frequently requested

**Comment by bcogrel** [comment]
See the table in http://research.bcgl.fr/pdfs/ontop-iswc20.pdf (holds for 4.0).

**Comment by apano-on** [comment]
A new page has been added describing SPARQL 1.1. and OGC GeoSPARQL 1.0 compliance and can be found at https://ontop-vkg.org/guide/compliance.html.

It has not yet been added to the navigation pane, so once all comments/changes are incorporated it will become visible.

**Comment by bcogrel** [comment]
Perfect, thanks! 

I have enriched and integrated it.
